name: Build and Release Electron App

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-and-release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Build and Publish Electron app
              shell: bash
              run: |
                  if [ "${{ matrix.os }}" = "windows-latest" ]; then
                    bun run build:win
                  elif [ "${{ matrix.os }}" = "macos-latest" ]; then
                    bun run build:mac
                  elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
                    bun run build:linux
                  fi
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
